V2.11.0 rc1 fixes
AttorneyOnline/AO2-Client pull request #1029
Opened 2024-07-28 23:10 UTC by Salanto

Fixes some minor issues in 2.11 RC1

2024-07-30 15:09 UTC, stonedDiscord requested changes

2024-07-30 15:09 UTC, stonedDiscord commented on src/widgets/moderator_dialog.cpp
> +const int day = 86400;
surely, qt already has a solution for this

2024-07-30 15:09 UTC, stonedDiscord commented on src/widgets/moderator_dialog.cpp
> +      qint64 unix_duration = ui_duration_mm->value() * minute + ui_duration_hh->value() * hour + ui_duration_dd->value() * day;
literally unreadable

2024-07-31 00:25 UTC, Salanto commented
This looks even worse, ngl, u sure I can't just use const int to make the conversions and cleanup the addition part a bit?

2024-07-31 09:54 UTC, stonedDiscord commented
I think this is acutally better, the oneliner was very dense.
Now it's clear how the values from the box get converted to what the box says, then to seconds and finally get added up.

2024-07-31 09:54 UTC, stonedDiscord approved these changes

2024-07-31 09:55 UTC, Salanto commented
Works for me

2024-07-31 09:55 UTC, merged