Add desk_mods 2 and 3 for more flexibility in emotes
AttorneyOnline/AO2-Client pull request #353
Opened 2020-12-17 16:45 UTC by in1tiate

Yet another change that breaks tsuserver validation, so here's the PR for that: https://github.com/AttorneyOnline/tsuserver3/pull/133

`desk_mod 2`: Hides the overlay during preanimation, shows it again once the preanim is finished.

`desk_mod 3`: Shows the overlay *only* during the preanim, and hides it when it ends.

2020-12-17 18:42 UTC, oldmud0 commented
What's the use case for desk mod 5?

2020-12-17 19:13 UTC, in1tiate commented
I use it to prevent eventual complaints about not having it.

2020-12-17 22:06 UTC, oldmud0 approved these changes
Looks good, the code's not gonna get any better than this. One refactoring opportunity here is to introduce enums to track the various desk modes, but that's up to you if you want to pursue it (it looks fine how it is right now).

2020-12-17 22:08 UTC, in1tiate commented on include/courtroom.h
>    void set_scene(QString f_desk_mod, QString f_side);
ah yes. hardcode city

2020-12-28 17:55 UTC, oldmud0 commented
Re-reviewed this. Older versions of tsuserver will silently drop messages that do not support this new `msg_type` (should be called `desk_mod` - I'll have to update the docs). I strongly recommend a feature flag so the client can transform that parameter to something that won't fail input validation.

2020-12-28 17:55 UTC, oldmud0 requested changes
Re-reviewed this. Older versions of tsuserver will silently drop messages that do not support this new msg_type (should be called desk_mod - I'll have to update the docs). I strongly recommend a feature flag so the client can transform that parameter to something that won't fail input validation.

2021-01-09 18:30 UTC, oldmud0 approved these changes

2021-01-09 18:32 UTC, merged