Fix blankposts not showing up in logs
AttorneyOnline/AO2-Client pull request #400
Opened 2021-01-12 10:54 UTC by Crystalwarrior

2021-01-12 11:28 UTC, stonedDiscord commented
i think that was a feature at some point

2021-01-12 22:58 UTC, oldmud0 requested changes
Why did you have to write a cursor? Why can't you just call `.size() - 1`

2021-01-13 21:36 UTC, Crystalwarrior commented
> Why did you have to write a cursor? Why can't you just call `.size() - 1`

View desync

2021-01-13 22:05 UTC, oldmud0 commented
> > Why did you have to write a cursor? Why can't you just call `.size() - 1`
> 
> View desync

Wait but you only access one element which is like the "last logged message." Why can't you store that. I'm trying to avoid an issue later on forgetting to increment/decrement something and causing an OOB.

2021-01-13 22:38 UTC, Crystalwarrior commented
> > > Why did you have to write a cursor? Why can't you just call `.size() - 1`
> > 
> > View desync
> 
> Wait but you only access one element which is like the "last logged message." I think you should store that value directly instead. I'm trying to avoid an issue later on forgetting to increment/decrement something and causing an OOB.

![Screenshot_20210114_013828.jpg](https://user-images.githubusercontent.com/3470436/104518741-380cf600-5609-11eb-8fd9-587d09f1d109.jpg)

2021-01-18 14:58 UTC, Crystalwarrior commented
Figured out a better method lol

2021-01-18 14:59 UTC, stonedDiscord approved these changes
the counter is gone and there's less lines

2021-01-18 18:35 UTC, oldmud0 approved these changes

2021-01-18 18:35 UTC, oldmud0 commented on src/courtroom.cpp
> +    QString message = item.get_message();
(We discussed that this is trimmed beforehand, so all blankposts are guaranteed to be empty strings.)

2021-01-18 18:35 UTC, oldmud0 commented on src/courtroom.cpp
> +  if (f_message.isEmpty() && last_ic_message == f_displayname + ":")
Duplicate comment with different conditions. Not questioning anything

2021-01-18 18:35 UTC, merged