Fix change character lag, bg resizing and repos weirdness, inconsistent behavior, sticker setting etc.
AttorneyOnline/AO2-Client pull request #473
Opened 2021-02-16 08:34 UTC by Crystalwarrior

See commits for changelog

2021-02-16 16:45 UTC, in1tiate approved these changes
seems fine to me

2021-02-21 16:59 UTC, oldmud0 requested changes
So far I've encountered a crash condition if you set the position with /pos, switch characters to one whose default position is different, and chat.

2021-02-22 10:37 UTC, Crystalwarrior commented on src/courtroom.cpp
> +        filename = "guilty_bubble";
yeah there is, it's called animated themes

2021-02-22 10:38 UTC, Crystalwarrior commented on src/lobby.cpp
> +//  ui_server_list->setHeaderHidden(true);
we talked about this on discord so resolving
(being able to easily reset to show the intended master-server ordering is important, as pressing the "refresh" button to reset that ordering is jank as hell)

2021-02-22 10:39 UTC, Crystalwarrior commented
> 
> 
> So far I've encountered a crash condition if you set the position with /pos, switch characters to one whose default position is different, and chat. Haven't finished reviewing everything though.

yeah wasn't this an issue w/ the outdated server software that particular server was using instead? You mentioned they run their soft on this commit https://github.com/AttorneyOnline/tsuserver3/commit/41bd23e1c28c1fb444385ece02ec3464d6a1b054

2021-02-22 18:20 UTC, oldmud0 commented
Yeah the review is old sorry.

2021-02-24 16:25 UTC, oldmud0 approved these changes
This all looks fine after testing. One thing I haven't really tested are stickers but the feature is trivial and doesn't need much testing anyway.

2021-02-24 16:26 UTC, oldmud0 commented
Let's get this bad boy merged. Please try to avoid sticking multiple fixes and features in one PR next time, I know you like to go on a roll but this slows things down in the long run.

2021-02-24 16:26 UTC, merged