Fix demo playback inaccuracies and jank. Start recording Timer packets and Evidence packets
AttorneyOnline/AO2-Client pull request #494
Opened 2021-03-19 18:25 UTC by Crystalwarrior

⚠HUGE, VERY IMPORTANT FIX⚠
Fix demo playback being incorrectly timed due to the misplaced order of the wait#% packet (it should go BEFORE the appended message, not AFTER! We're delaying the message we're *writing*, not the *next message*!!!)

Additionally, this PR makes demo playback actually record the Timer packets (since I forgot to do that 😳), as well as accurately use /max_wait and the skips it causes to adjust the timers themselves as well.
/min_wait is also now deprecated - people shouldn't use it now that min_wait can be enforced on the client-side instead.

Also, fix Demo Playback not using utf-8 codec during parsing of the demo file, causing special characters like emoji and Russian text not being shown correctly (I wish Demo Playback was not useless to non-English speaking servers on 2.9 release but here we go! At least we fixed .log's... and the .demo's themselves are still saved correctly).

Fix a weird and useless static_cast to int when setting timers when they're supposed to be qint64 (basically useless conversion that could have resulted in potential loss of data)

I also feel very happy having figured this out LOL

2021-03-19 18:40 UTC, in1tiate reviewed
looks good to me, i'll leave it to @oldmud0 to approve though

2021-03-19 18:40 UTC, in1tiate commented on src/courtroom.cpp
> +// Used by demo playback to adjust for max_wait skpis
```suggestion
// Used by demo playback to adjust for max_wait skips
```

2021-03-20 15:55 UTC, oldmud0 commented on src/aoapplication.cpp
> +
Why not connect skip_timers directly from the demo server to the courtroom when AOApplication is constructing the courtroom?

2021-03-20 15:56 UTC, oldmud0 commented
Also, I told you not to make those behemoth commits...

2021-03-20 17:34 UTC, Crystalwarrior commented
> 
> 
> Also, I told you not to make those behemoth commits... One feature/fix/change per commit please. At most two.

Fixed it 😳

2021-03-20 17:46 UTC, oldmud0 requested changes
Build error: `error C2065: 'min_wait': undeclared identifier`

2021-03-21 02:10 UTC, oldmud0 approved these changes

2021-03-21 02:12 UTC, merged