Fix character select screen lag/performance overhead
AttorneyOnline/AO2-Client pull request #504
Opened 2021-03-24 20:08 UTC by Crystalwarrior

Caused by Animated Elements being initialized for a metric fuckton of AOImages used by the character select screen. It might be related to excessive File I/O that has to still fall back to static sprites, but this PR instead chooses to simply not allow animated elements for character selectors/overlays and evidence selectors/overlays.

2021-03-26 05:37 UTC, oldmud0 commented
Haven't tested for stability on Linux yet. Need to do so before merging.

2021-03-29 04:49 UTC, oldmud0 commented
Nope. Does not fix issues on Linux.

2021-03-29 04:49 UTC, oldmud0 requested changes
Does not fix issues on Linux.

2021-04-01 10:57 UTC, Crystalwarrior commented
wait, so QMovie() being created causes performance overhead???

2021-04-03 20:28 UTC, Crystalwarrior commented
Yeah this did nothing to fix it, more R&D needed

2021-04-11 20:38 UTC, oldmud0 commented on src/aoimage.cpp
> +    movie = new QMovie();
Wait has this been leaking memory this whole time? This needs to be parented. Bruh moment.
```cpp
movie = new QMovie(this);
```

2021-04-20 05:20 UTC, oldmud0 approved these changes

2021-04-20 05:20 UTC, merged