Fix demo server not being added if serverlist.txt is missing, add translation support to demo server messages
AttorneyOnline/AO2-Client pull request #514
Opened 2021-03-30 16:02 UTC by in1tiate

2021-03-30 21:01 UTC, Crystalwarrior submitted a review, later dismissed
All checks failed, the thing doesn't compile

2021-03-31 02:47 UTC, oldmud0 requested changes

2021-03-31 02:47 UTC, oldmud0 commented on src/demoserver.cpp
> +            }
Extra brace
```suggestion
```

2021-03-31 03:43 UTC, oldmud0 approved these changes
brace for it

2021-03-31 03:44 UTC, merged