Add a new dialog box for sending login information to the server
AttorneyOnline/AO2-Client pull request #544
Opened 2021-04-28 00:21 UTC by MangosArentLiterature

This PR adds LoginDialog, a dialog box for inputting a username and password, and sending it to the server, removing the need to use sever commands (and thus, removing the potential to accidentally leak moderator passwords). The login dialog will send an AUTH packet to the server, containing the username and password. (If a server doesn't support usernames, the username field can be left empty).

Servers can implement support for this by adding support for the AUTH packet. The first parameter in the packet is for usernames, the second is for passwords. If your server doesn't support usernames, the first parameter in the packet can be discarded.

* Rename debug_functions to dialog_functions
* Add LoginDialog
* Add a new button to courtroom.cpp for opening the login dialog.

2021-04-28 00:24 UTC, MangosArentLiterature commented
I've tested this, and it all seems to work fine. You can find an experimental branch of Akashi that supports this at https://github.com/AttorneyOnline/akashi/tree/experimental-login-changes

2021-04-29 03:28 UTC, oldmud0 requested changes
I have design questions:

- This is totally convincing and secure, in the sense that it unfortunately is not. If you want to improve security, you should disable `/login` and also enhance `AUTH` to use something like challenge-response authentication.
- This needs to be behind a feature flag or otherwise it will confuse players, as tsuserver neither supports `AUTH` nor uses usernames.

2021-04-29 03:28 UTC, oldmud0 commented on src/dialog_functions.cpp
> +void LoginDialog::setupUi()
For more complicated dialogs, let's use UIC, please. That way we don't have to write the UI in a C++ mess.

2021-04-29 03:28 UTC, oldmud0 commented on src/dialog_functions.cpp
> +    labelPassword->setBuddy(editPassword);
Please use `tr()` instead of `QCoreApplication::translate`

2021-04-29 03:28 UTC, oldmud0 commented on src/courtroom.cpp
> +    ao_app->send_server_packet(new AOPacket("AUTH", packet_contents));
This is totally convincing and secure.

2021-04-30 00:04 UTC, MangosArentLiterature commented
This was great until I realized its actually really terrible. Marking this as a draft until I've implemented a better way of securing the communication.

2021-07-21 04:28 UTC, closed without merging