Add support for mounting multiple base folders
AttorneyOnline/AO2-Client pull request #554
Opened 2021-06-05 20:33 UTC by oldmud0

This feature introduces the ability for players to mount multiple base folders in addition to the main AO base folder. When an asset is not found in the main base folder, the list of mounted base folders is searched in order to find the asset.

This can be used to split up assets belonging to various servers and configure an order of precedence when two character folders conflict [1]. It can also be used to store a small subset of characters locally, and then have the rest of the characters be located on another drive or even a network location (as long as it is mounted as an OS drive).

This feature does not introduce any breaking changes. Only setting files (e.g. callwords.ini, serverlist.txt) will continue to be limited to the main base folder.

[1]: For now, file format takes primary precedence and then mounting order, due to the way things are scanned. The file format precedence order is .webp, .apng, .gif, and .png. So, even if a .webp is located in a mount path with less priority than a .gif in a mount path with more priority, the .webp will be chosen. This is a simpler design than the "intuitive" behavior, but if issues arise, I may change it.

2021-06-06 05:25 UTC, in1tiate submitted a review, later dismissed
comes with some welcome improvements to path resolution, i am a fan of this

2021-06-06 17:10 UTC, Crystalwarrior commented on include/aoapplication.h
> +
what is this black magic
holy  crap, ao2 using actual c++

2021-06-06 17:11 UTC, Crystalwarrior commented on include/aoapplication.h
> +  QString get_real_path(const VPath &vpath);
get_real()

2021-06-06 17:16 UTC, Crystalwarrior requested changes
Lots of sweeping changes across path resolution in this PR, you should make sure to test that all of the pre-existing behavior is not broken. Perhaps a pre-release can be put out so people can report bugs swiftly

Also, dunno why you commented out default stylesheet settings for AO App object
Cache is cool and good though, there's some giga brain stuff in here I don't fully understand lol

2021-06-06 17:16 UTC, Crystalwarrior commented on src/aoapplication.cpp
> +  // qApp->setStyleSheet("QFrame {background-color:transparent;} QAbstractItemView {background-color: transparent; color: black;}; QLineEdit {background-color:transparent;}");
Why was this commented out? This was added to make sure that outdated themes with .css don't break old behavior.

2021-06-06 19:20 UTC, in1tiate commented
needs more testing eh? one hell of a change of pace from pre-2.9.1

2021-06-07 12:07 UTC, Crystalwarrior commented on src/aoapplication.cpp
> +  // qApp->setStyleSheet("QFrame {background-color:transparent;} QAbstractItemView {background-color: transparent; color: black;}; QLineEdit {background-color:transparent;}");
Set it on the courtroom itself maybe rather than the app?

2021-06-07 12:08 UTC, Crystalwarrior commented on src/aoapplication.cpp
> +  // qApp->setStyleSheet("QFrame {background-color:transparent;} QAbstractItemView {background-color: transparent; color: black;}; QLineEdit {background-color:transparent;}");
Set Default style sheet on the court and we Gucci

2021-06-07 12:09 UTC, Crystalwarrior requested changes
Set Default style sheet on the court and we Gucci

2021-06-09 03:52 UTC, oldmud0 commented
@Crystalwarrior gucci?

2021-06-09 10:12 UTC, Crystalwarrior commented
> @Crystalwarrior we gucci?

I said court not lobby. Just do both

2021-06-10 00:20 UTC, Crystalwarrior approved these changes
Ye

2021-06-10 00:41 UTC, oldmud0 commented
yey

2021-06-10 00:41 UTC, merged