Multithreaded character/music loading
AttorneyOnline/AO2-Client pull request #583
Opened 2021-08-13 09:12 UTC by in1tiate

quick and dirty, about a 33% decrease in loading times here at the cost of slightly less informative loading screens

2021-09-23 00:26 UTC, oldmud0 requested changes
going through some old open PRs. don't think this needs multithreading actually

2021-09-23 00:26 UTC, oldmud0 commented on include/aoapplication.h
> +  QWaitCondition musicLoaded;
you don't need these monitors

2021-09-23 00:26 UTC, oldmud0 commented on src/packet_distribution.cpp
> +    char_mutex.unlock();
use `charsLoaded.waitForFinished()`, but note that both your code and waitForFinished are going to block the main thread which will look like freezing.

so, maybe what you really want is a `QFutureWatcher` where when both futures are done, you then mark the loading process as finished.

however, at second glance, I'm not really seeing any I/O intensive parts in either of those two "loading" functions?

2021-09-23 00:26 UTC, oldmud0 commented on src/packet_distribution.cpp
> -                                    .arg(QString::number(char_list_size)));
I think this was your bottleneck, not the loop itself

2021-11-16 04:11 UTC, in1tiate commented
dont think this is really necessary after all, closing

2021-11-16 04:11 UTC, closed without merging