Added version to window title.
AttorneyOnline/AO2-Client pull request #613
Opened 2021-12-07 21:19 UTC by Pyraqq

Also updated the translation files for missing strings and updated the Polish translation.

2021-12-07 21:26 UTC, Pyraqq commented
The version number is missing however from demo playback. I plan to fix this soon.
![obraz](https://user-images.githubusercontent.com/46277816/145107994-7c59bfd8-815d-4606-bb19-8b4d031b61ba.png)

2021-12-09 02:13 UTC, oldmud0 requested changes

2021-12-09 02:13 UTC, oldmud0 commented on src/lobby.cpp
> +  this->setWindowTitle(tr("Attorney Online ") + ao_app->applicationVersion());
```suggestion
  this->setWindowTitle(tr("Attorney Online %1").arg(ao_app->applicationVersion()));
```

2021-12-09 02:13 UTC, oldmud0 commented on src/packet_distribution.cpp
> +    window_title = tr("Attorney Online");
```suggestion
    window_title = tr("Attorney Online %1").arg(applicationVersion());
```

2021-12-09 02:13 UTC, oldmud0 commented on src/packet_distribution.cpp
> +        window_title += " " + applicationVersion() + ": " + server_name;
```suggestion
        window_title += ": " + server_name;
```

2021-12-23 22:53 UTC, oldmud0 approved these changes

2021-12-23 22:53 UTC, merged