Add server description to favourites, if supported by server.
AttorneyOnline/AO2-Client pull request #648
Opened 2022-02-14 12:43 UTC by Salanto

Mitigates #646 by accepting descriptions during the placercount handshake.

2022-02-14 20:53 UTC, Salanto commented
SV and SCC both do not seem to exist anymore, so PN it is.

2022-02-15 00:03 UTC, oldmud0 approved these changes
This is horrible. I just realized a terrible use case for this. Marquees and ASCII movies

Anyway approved, just make sure to update the docs

2022-02-15 00:03 UTC, oldmud0 commented on src/lobby.cpp
> +    ui_description->append_linked(server_description);
```suggestion
    ui_description->clear();
    ui_description->append_linked(server_description);
```
Then go into `on_server_list_clicked` and replace the same set of lines with a call to `set_server_description`

2022-02-15 00:04 UTC, oldmud0 requested changes
Why did I mark this as approved. I meant to mark it as changes requested

2022-02-15 14:15 UTC, oldmud0 approved these changes

2022-02-15 14:15 UTC, merged