Fix messy window title and make it all nice and pretty
AttorneyOnline/AO2-Client pull request #705
Opened 2022-03-25 15:12 UTC by Crystalwarrior

Before:
![Attorney_Online_ll0Jvstd1V](https://user-images.githubusercontent.com/3470436/160148236-0cf65aa1-cf5b-44c8-8afd-27dc99644511.png)

After:
![Attorney_Online_sTetZk6tUH](https://user-images.githubusercontent.com/3470436/160148241-9d2c0468-a72c-461c-886d-b79f24765d0e.png)

2022-04-11 04:46 UTC, oldmud0 requested changes

2022-04-11 04:46 UTC, oldmud0 commented on src/packet_distribution.cpp
> +        window_title = server_name;
can you fix this if block real quick to remove the duplicate code? just tryna leave things better than the way we found them. thanks

2022-05-23 18:41 UTC, stonedDiscord commented
using a pointer to fix the duplicate code makes it hang

i'd say this is necessary in this case because it's using the 2 different lists

2022-05-23 18:41 UTC, stonedDiscord approved these changes

2022-05-23 18:42 UTC, merged