Stop iniswapping from modifying the char.ini file
AttorneyOnline/AO2-Client pull request #712
Opened 2022-03-27 22:08 UTC by Crystalwarrior

Stop iniswapping from modifying the char.ini (which can potentially remove comments such as credits, charmaker notes, etc.)
It also lead to really annoying behavior where if you swapped out from that character, when you swap back you'd be put into the iniswap instead of the default state, which could even be outside that character's iniswap list.

2022-04-11 13:34 UTC, oldmud0 reviewed
I'm glad we are removing one of the most nerve wracking parts of courtroom.cpp. The function that returns a name given a name

2022-05-21 14:08 UTC, stonedDiscord approved these changes
it did WHAT before

2022-06-06 17:55 UTC, stonedDiscord submitted a review, later dismissed

2022-07-16 13:41 UTC, stonedDiscord commented
what happened with `get_char_name`

2022-07-17 20:51 UTC, oldmud0 requested changes

2022-07-17 20:51 UTC, oldmud0 commented on src/text_file_functions.cpp
> -
I'd like to accept this PR but `get_char_name` is still depended on according to the linker. Please bring it back or remove references to it.

2022-07-26 21:08 UTC, TrickyLeifa submitted a review, later dismissed

2022-07-26 21:08 UTC, TrickyLeifa commented on src/courtroom.cpp
>        ao_app->get_list_file(ao_app->get_base_path() + "iniswaps.ini");
This causes duplicate entries when editing the iniswaps.ini
[bugs.webm](https://user-images.githubusercontent.com/26681464/181112303-8a31c5e6-f169-477e-ba78-84264e535d25.webm)
.

2022-07-30 00:43 UTC, oldmud0 approved these changes
Good riddance

2022-07-30 00:45 UTC, merged