Disable DPI scaling for good
AttorneyOnline/AO2-Client pull request #769
Opened 2022-05-20 00:30 UTC by Crystalwarrior

AO2 has not been properly designed to support DPI scaling, and it's been causing nothing but issues with themes breaking by text going out of bounds etc.

2022-05-21 13:58 UTC, stonedDiscord commented
this code block tries to fix the problem and you want to remove it

2022-05-21 13:58 UTC, stonedDiscord requested changes
this code block tries to fix the problem and you want to remove it

2022-05-21 17:29 UTC, Crystalwarrior commented
> this code block tries to fix the problem and you want to remove it

bro this code block is the direct cause of the issue isn't it

2022-05-23 18:45 UTC, stonedDiscord commented
whatever

2022-05-23 18:45 UTC, merged

2022-05-27 01:29 UTC, oldmud0 commented
just so you know, this won't prevent windows from scaling the program, but rather it will fall back to bilinear scaling

2022-06-20 23:06 UTC, Crystalwarrior commented
> just so you know, this won't prevent windows from scaling the program, but rather it will fall back to bilinear scaling but you probably already know that

Wait I didn't know that lol