Add Emote preview
AttorneyOnline/AO2-Client pull request #774
Opened 2022-06-02 17:44 UTC by Crystalwarrior

https://user-images.githubusercontent.com/3470436/171692940-6277bb65-c90a-4967-89b8-fff08c420fbe.mp4

Emote preview window can be resized, is affected by flip/pre settings, and you can also use the right-click dropdown to select specific emote types (preanim, talk (b), idle (a), segway (c))

2022-06-02 17:56 UTC, Salanto commented on src/aoemotepreview.cpp
> +//  ui_vp_background = new BackgroundLayer(ui_viewport, ao_app);
Do we really need to keep those commented out lines around?

2022-06-06 17:26 UTC, stonedDiscord commented
wait this opens an extra window?

2022-06-12 00:16 UTC, Salanto commented
> wait this opens an extra window?

It opens an independent window from the main client to display a character inside it. That window is scalable and keeps its scale when switching between emotes.

2022-06-16 03:19 UTC, oldmud0 commented
This is failing the builds. Please fix.

2022-07-16 15:47 UTC, Salanto requested changes

2022-07-18 19:29 UTC, stonedDiscord commented
are they supposed to be animated

2022-07-19 07:14 UTC, stonedDiscord approved these changes

2022-07-21 20:24 UTC, Salanto approved these changes

2022-07-23 15:18 UTC, merged

2022-07-23 21:31 UTC, oldmud0 commented
This looks cool. Maybe for next version we can put the size on the title bar so it doesn't obstruct the preview?