Introducing custom blips: as easy as a custom showname!
AttorneyOnline/AO2-Client pull request #780
Opened 2022-06-05 13:34 UTC by Lernos

Requires modifications from server owners for their servers to include 'custom_blips' in their "FL" packet and a new "validation monstrosity" to include a new string called blipname which must be added to the IC message args processed by the server. For backwards compatibility I suggest setting blipname as a server-side args variable to an empty string "" by default, since older clients will send nothing. In that case, the client will read the char.ini file to determine the correct blips/gender instead of looking it up in the new IC message packet.

2022-06-05 14:45 UTC, Lernos commented
I know, clang-tidy, I don't love you either.

2022-07-07 13:21 UTC, in1tiate commented
This does not need to be part of the IC validation hell string, and as a whole blips do not need to be networked. Voting for closure.

2022-07-07 13:25 UTC, Lernos commented
Why do they not need to be networked though? We allow to play custom SFX on any message, but not blips? How about the fact that canonically, Godot can imitate voices of other characters, Ted Tonate can speak either as a "ddmale" or "tonate" typing on his keyboard, Robin changes from male to female voice after her transformation, if you want to have an invisible narrator ("Anon" type of character), you'd have to make one for **each** blipvoice? These things are all important to players I know. Changing a character's blips to any other blips on the fly seems like a very nice customization option.

2022-07-14 23:01 UTC, Salanto commented
This is double edged.
It has terrible abuse potential, but at the same time is very flexible frame_sfx is already being used to earrape everyone around them and I doubt this would fare much better.

2022-07-15 03:30 UTC, in1tiate commented
> Why do they not need to be networked though? We allow to play custom SFX on any message, but not blips? How about the fact that canonically, Godot can imitate voices of other characters, Ted Tonate can speak either as a "ddmale" or "tonate" typing on his keyboard, Robin changes from male to female voice after her transformation, if you want to have an invisible narrator ("Anon" type of character), you'd have to make one for **each** blipvoice? These things are all important to players I know. Changing a character's blips to any other blips on the fly seems like a very nice customization option.

I hadn't considered characters with multiple blip types, which is a feature the unofficial 2.5 client had and which we currently still lack. With that in mind I'm in favor of this change.

2022-07-15 03:33 UTC, in1tiate requested changes
See above; please avoid adding clutter to the main UI

2022-07-27 16:52 UTC, TrickyLeifa commented
I'd recommend linking a server pull-request that introduces the network changes so that it's easier to test the changes; and vice versa.

2022-07-29 02:05 UTC, oldmud0 reviewed
Looks fine but seems abusable - e.g. set blip name to `../music/zettaslow`.

Also looking for the serverside PR for this.

Also put that profile picture away.

2022-07-29 02:05 UTC, oldmud0 commented on src/courtroom.cpp
> +    else { packet_contents.append(ui_custom_blips->text()); }
Please keep your if blocks unfolded

2022-07-29 02:06 UTC, oldmud0 commented on src/courtroom.cpp
> +  ui_custom_blips = new QLineEdit(this);
Oh yeah also this definitely should be a dropdown. It's not ideal to just throw the player into the darkness and make them scroll through the files themselves.

2022-08-01 09:24 UTC, Salanto commented
By the by, @Lernos. You could join the Discord to make communication a bit easier.

2022-08-01 15:02 UTC, Crystalwarrior commented
> Looks fine but seems abusable - e.g. set blip name to `../music/zettaslow`.
> 
> Also looking for the serverside PR for this.
> 
> Also put that profile picture away.

Well servers should sanitize it in that case lmao

2022-08-02 04:00 UTC, Lernos commented
> Also put that profile picture away.

Sorry xD

> By the by, @Lernos. You could join the Discord to make communication a bit easier.

Oh, I actually am. I was just dealing with stuff IRL. Not sure it would make communications that much easier, but whatever's more convenient.

> Also same, serverside PR would be nice

There you go. I don't work with akashi, but I'm pretty sure it can be figured out. There should be a similar mechanism there somewhere, right?
AttorneyOnline/tsuserver3#198

2022-08-02 07:55 UTC, Salanto commented
I'll handle Akashi. You might want to resolve those merge conflicts tho.

2022-09-02 23:22 UTC, stonedDiscord commented
> Oh yeah also this definitely should be a dropdown. It's not ideal to just throw the player into the darkness and make them scroll through the files themselves.

but which sounds should the dropdown contain?

1. create an` .ini` file that defines which one should be
2. every .opus file in `base\sounds\blips`
3. every file in `base\sounds\general` that starts with `sfx-blip`
4. every file from every subfolder in `base\sounds\blips`
5. all of the above

if we go with 5, what to do about the list getting too long?

2022-09-07 02:32 UTC, oldmud0 commented
I would go with 2 although it wouldn't be much additional effort to go with 4.

2024-05-09 03:36 UTC, in1tiate commented
I plan on pulling the network changes from this pull request into the code I'm writing for #952 unless there are any objections. I will not be including the UI changes, as they are outside the scope of that issue.

2024-05-16 12:38 UTC, Salanto commented
Stale PR + Implemented in a different PR

2024-05-16 12:38 UTC, closed without merging